### ISSUE TITLE
Songs are still unavailable

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [ivan-leontiev/clementine-free-grooveshark#1]
Seeing as clementine doesn't have a debugging console, I can't tell you what errors, if any, your branch is giving. However, I thought this would allow me to sign in and access songs from grooveshark, but it's still not playing them...

**Comment by ivan-leontiev** [comment]
Try to run clementine from console with --verbose option passed. For more verbose output you can build debug version of clementine:
- cd Clementine/build
- cmake -DCMAKE_BUILD_TYPE=Debug ../
- make

**Comment by neurodiverseEsoteric** [comment]
Thanks, I keep forgetting to look for a --verbose option for this sort of thing. I think there might be enough information from the verbose output to share what's going on, but I don't know how much of it you want. It looks like the problem boils down to the URL handler's string that's being passed; it is basically giving an empty string in return.

```
URL handler for  QUrl( "grooveshark://87525/6327535/24330175" )  returned  QUrl( "" )  
```

There's a bunch of login data that I'm not sure is safe to post up here, but does this tell you enough already?

**Comment by ivan-leontiev** [comment]
I've tried to find the song by ids in the URL you provided and I've got:
artist [87525]: "Alfred Brendel"
album [6327535]: "Beethoven: Favourite Piano Sonatas"

but there is no song with the id 24330175!
So how this song appeared in the playlist? Maybe you import it from an old playlist. Is this the only song that can't be played?
Please choose a few songs from the "popular songs" or from search and try to play them. And then send to me log lines that contain the string "getStreamKeyFromSongIDEx".

**Comment by neurodiverseEsoteric** [comment]
Actually, nothing seems to be playing even on Grooveshark itself. Every song link is returning the "#notfound" page...

**Comment by neurodiverseEsoteric** [comment]
And now, for some reason, that exact same track is now playable in Clementine. Maybe Grooveshark rearranged their databases, or something? I played it from the search results list, not my own playlists on Grooveshark, though. I haven't tried playing from them just yet...

**Comment by ivan-leontiev** [comment]
I've encountered with this too. After a while listening to music with clementine  Grooveshark seems ban my ip and then all songs on Grooveshark returns notfound page. Think I need to review communication with their api.

**Comment by neurodiverseEsoteric** [comment]
Ah, so this is still what I guess is called a "throttling" issue? Is going through their API the only means of remotely accessing Grooveshark?

**Comment by ivan-leontiev** [comment]
Yes, you are right this is a throttling issue. I've pushed some changes, please try it and let me know if the issue still there.

**Comment by neurodiverseEsoteric** [comment]
The changes didn't work for me, I'm afraid...

**Comment by ivan-leontiev** [comment]
So any song in your Grooveshark playlists can't be played by clementine as well as any song returned from search results? And when you go to Grooveshark website it also can't playing songs and every song link returning notfound page? Maybe you already have been banned by Grooveshark before you tried to run clementine.

**Comment by neurodiverseEsoteric** [comment]
I didn't try logging into Grooveshark directly at the time, but both playlists and searched songs failed for me. I can access songs from Grooveshark's website right now, though.

**Comment by ivan-leontiev** [comment]
I found that there is also Grooveshark's issue. It sometimes return dead songs e.g. try to search "the strokes" then in search results select "Machu Picchu" song(it likely to be first). That song can't be played with clementine and Grooveshark itself also song link returns notfound page. But go to the "The Strokes" artist page on Grooveshark and find that song. It can be played by Grooveshark and clementine.

**Comment by neurodiverseEsoteric** [comment]
Can Clementine have a built-in auto-song-resolution feature? The songs that are still "live" on Grooveshark and in my playlists, still appear as "dead" in Clementine...

**Comment by ivan-leontiev** [comment]
What do you specifically expect from auto-song-resolution feature? Can you share to me your playlist?

**Comment by neurodiverseEsoteric** [comment]
Yes, I could email you the playlist id...

**Comment by ivan-leontiev** [comment]
Good, send it to leont.ivan@gmail.com

**Comment by neurodiverseEsoteric** [comment]
Well it now appears that I can't send them; Grooveshark has shut down entirely.
